baseURL = "https://mansoorbarri.com"
languageCode = 'en-us'
title = "Mansoor Barri"

pagination.pagerSize = 5
[menu]
  [[menu.main]]
    name = "blogs"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 2

[params]
  description = "known for a few things. developer of pdfthing, Hugo theme Validator, and a few other things."
  wiki = "likh."
  hero = "just a **techie**."
  search = false
  mainSections = ["blogs"]
  projects = [
      {name = "RadarThing", url = "https://radarthing.com", description = "A radar for GeoFS."},       
      {name = "vstrips", url = "https://github.com/mansoorbarri/geofs-vstrips", description = "a virtual ATC strips system for the GeoFS community."},
      {name = "pdfthing", url = "https://pdfthing.mansoorbarri.com", description = "a PDF utility done right."},       
  ]
  socials = [        
  {name = "github", url = "https://github.com/mansoorbarri"},
  {name = "linkedin", url = "https://www.linkedin.com/in/mansoorbarri/"},
  ]


